language: ruby
rvm:
  - 2.4.0

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - psql -c 'create database travis_ci_test;' -U postgres